repos:
  - repo: local
    hooks:
      - id: rust-check
        name: cargo check
        entry: cargo check
        language: system
        types: [rust]
        pass_filenames: false
      
      - id: rust-fmt
        name: cargo fmt
        entry: cargo fmt -- --check
        language: system
        types: [rust]
        pass_filenames: false
      
      - id: rust-clippy
        name: cargo clippy
        entry: cargo clippy -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false

      - id: rust-test
        name: cargo test
        entry: cargo test
        language: system
        types: [rust]
        pass_filenames: false
